[project]
name = "sportai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rochasar", email = "vnrocha07@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "openai>=3.8.0",
    "pypdf>=6.17.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
sportai = "sportai:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
